[title]
title = "Nerd"
name1 = "Nerd"
name2 = "lonelynerd"
catchphrase = "Welcome back..."
img = "https://avatars.githubusercontent.com/u/42437280?v=4"

[personal]
age = 19
pronouns = ["She/Them", "They/Them"]
desc = "C hater"

[colors]
bgimg = "https://imalonelynerd.fr/landing/images/bg.png"
bg1 = "#000000"
bg2 = "#000080"
bg3 = "#0000FF"
text = "#FFFFFFF"

[[urls]]
title = "Website"
url = "https://imalonelynerd.fr"

[[urls]]
title = "blahaj.land"
url = "https://blahaj.land"
