[title]
title = "Nerd"
catchphrase = "Welcome back..."
pronouns = [ "She/Them", "They/Them" ]
img = "https://avatars.githubusercontent.com/u/42437280?v=4"

[personal]
name1 = "Nerd"
name2 = "imalonelynerd"
age = 19
flags = [ "trans", "nb", "ace" ]
desc = "## *\"Special ability : putting too much effort into stupid things\"*\n\n**Cybesec** student, Hobbist **graphical designer**, **C hater**<br>\n### Languages, frameworks & softwares I'm using :\n\n- Python, JavaScript, PHP, Java, C (ew), OCaml\n- Node, Electron, VueJS, jQuery\n- Figma, Inkscape, Gimp\n\n### Projects :\n\n- **Talisman** ( webapp & GTK ), a stupid simple, yet elegant Yu-Gi-Oh! companion\n- **PrettyHeroes**, a simple and colorful About Me page creator. I'll let you guess why I named it this way...\n- **Frisk**, an online gallery, made to be a self-hostable DeviantArt alternative\n- **Blahaj ecosystem**, a serie of websites made for **blahaj.land**\n- **Oxygen²**, Oxygen reincarnated\n
"
work = "Student"
timezone = "UTC +2"
location = "Rouen, France"

[colors]
bgimg = "https://imalonelynerd.fr/landing/images/comet.jpg"
background = "#0c2121"
widget = "#0c2121"
link = "#004346"
hover = "#09bc8a"
title = "#44ffc7"
text = "#FFFFFF"

[[urls]]
title = "My website"
url = "https://imalonelynerd.fr"

[[urls]]
title = "My GitHub"
url = "https://github.com/lonelynerd"
