[title]
title = "Nerd"
img = "https://avatars.githubusercontent.com/u/42437280?v=4"
catchphrase = "Special ability : putting too much effort into stupid things"
pronouns = [ "They/Them" ]

[personal]
name1 = "Nerd"
name2 = "imalonelynerd"
age = 19
desc = "## Cybesec student<br>Hobbist graphical designer<br>On a C redemption arc<br>\n### Languages, frameworks & softwares I'm using :\n\n- Python, JavaScript, PHP, Java, C, OCaml\n- Node, Electron, VueJS, jQuery\n- Figma, Inkscape, Gimp\n\n### Projects :\n\n- **Talisman** ( webapp & GTK ), a stupid simple, yet elegant Yu-Gi-Oh! companion\n- **PrettyHeroes**, a simple and colorful About Me page creator. I'll let you guess why I named it this way...\n- **Blahaj ecosystem**, a serie of websites made for **blahaj.land**\n- **Oxygen²**, Oxygen reincarnated\n"
flags = [ "nb", "ace" ]
work = "Student"
timezone = "UTC +2"
location = "Rouen, France"

[colors]
background = "#e0aaff"
widget = "#c77dff"
link = "#c77dff"
hover = "#9d4edd"
title = "#5a189a"
text = "#10002b"
bgimg = "https://images.unsplash.com/photo-1616001089004-04948fc0e6c1?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[urls]]
title = "Lonely Island"
url = "https://imalonelynerd.fr"

[[urls]]
title = "GitHub"
url = "https://github.com/lonelynerd"