[title]
title = "Nerd"
catchphrase = "Special ability : putting too much effort into stupid things"
pronouns = [ "She/Them", "They/Them" ]
img = "https://avatars.githubusercontent.com/u/42437280?v=4"

[personal]
name1 = "Nerd"
name2 = "imalonelynerd"
age = 19
flags = [ "trans", "nb", "ace" ]
desc = "## Cybesec student<br>Hobbist graphical designer<br>On a C redemption arc<br>\n### Languages, frameworks & softwares I'm using :\n\n- Python, JavaScript, PHP, Java, C, OCaml\n- Node, Electron, VueJS, jQuery\n- Figma, Inkscape, Gimp\n\n### Projects :\n\n- **Talisman** ( webapp & GTK ), a stupid simple, yet elegant Yu-Gi-Oh! companion\n- **PrettyHeroes**, a simple and colorful About Me page creator. I'll let you guess why I named it this way...\n- **Blahaj ecosystem**, a serie of websites made for **blahaj.land**\n- **Oxygen²**, Oxygen reincarnated\n"
work = "Student"
timezone = "UTC +2"
location = "Rouen, France"

[colors]
bgimg = "https://images.unsplash.com/photo-1535408190508-be4c21946da6?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
background = "#260C4F"
widget = "#4C2286"
link = "#4C2286"
hover = "#9F62E4"
title = "#CF9BF7"
text = "#FFFFFF"

[[urls]]
title = "My website"
url = "https://imalonelynerd.fr"

[[urls]]
title = "My GitHub"
url = "https://github.com/lonelynerd"

[[urls]]
title = "blahaj.land"
url = "https://blahaj.land/"