[title]
title = "Nerd"
img = "https://avatars.githubusercontent.com/u/42437280?v=4"
catchphrase = "Special ability : putting too much effort into stupid things"
pronouns = [ "They/Them" ]

[personal]
name1 = "Nerd"
name2 = "imalonelynerd"
age = 19
desc = "## Cybesec student<br>Hobbist graphical designer<br>On a C redemption arc<br>\n### Languages, frameworks & softwares I'm using :\n\n- Python, JavaScript, PHP, Java, C, OCaml\n- Node, Electron, VueJS, jQuery\n- Figma, Inkscape, Gimp\n\n### Projects :\n\n- **Talisman** ( webapp & GTK ), a stupid simple, yet elegant Yu-Gi-Oh! companion\n- **PrettyHeroes**, a simple and colorful About Me page creator\n- **Oxygen²**, Oxygen reincarnated\n"
flags = [ "nb", "ace" ]
work = "Student"
timezone = "UTC +2"
location = "Rouen, France"

[colors]
background = "#002628"
widget = "#004346"
link = "#004346"
hover = "#508991"
title = "#09BC8A"
text = "#FFFFFF"
bgimg = "https://images.unsplash.com/photo-1605286700104-15889419f60b?q=80&w=1646&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"

[[urls]]
title = "Lonely Island"
url = "https://imalonelynerd.fr"

[[urls]]
title = "GitHub"
url = "https://github.com/lonelynerd"

[[urls]]
title = "Talisman"
url = "https://talisman.imalonelynerd.fr/"

[[urls]]
title = "PrettyHeroes"
url = "https://heroes.imalonelynerd.fr/"

[[urls]]
title = "EventHorizon"
url = "https://horizon.imalonelynerd.fr/"