[title]
title = "Nerd"
name1 = "Nerd"
name2 = "lonelynerd"
catchphrase = "Welcome back..."
img = "https://avatars.githubusercontent.com/u/42437280?v=4"

[personal]
age = 19
pronouns = ["She/Them", "They/Them"]
desc = "CS student <br/>Hobbist graphical designer<br/>C hater<br/><br/>Special ability : putting too much effort into stupid things<br/>Working on Talisman and Frisk"

[colors]
bgimg = "https://imalonelynerd.fr/landing/images/bg.png"
background = "#000000"
widget = "#000080"
link = "#008000"
hover = "#0000FF"
title = "#00FF00"
text = "#FFFFFF"

[[urls]]
title = "Website"
url = "https://imalonelynerd.fr"

[[urls]]
title = "GitHub"
url = "https://github.com/lonelynerd"

[[urls]]
title = "blahaj.land"
url = "https://blahaj.land"
